spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:propertize_db}
    username: ${POSTGRES_USER:dbuser}
    password: ${POSTGRES_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka/

logging:
  level:
    com.propertize.payment: INFO
